language: go

go:
    - master

env:
    global: 
        - GO111MODULE=on

stages:
    - test

jobs:
    include:
        - stage: test
          script:
            - go get -u golang.org/x/lint/golint
            - go install golang.org/x/lint/golint
            - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.12.5
            - golint ./...
            - golangci-lint run
        - script:
            - go get github.com/mattn/goveralls
            - go install github.com/mattn/goveralls
            - go test -race -covermode=atomic -coverprofile=coverage.out ./...
            - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
